### ISSUE TITLE
Navigation Menu 위치

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC2-Team7-Larasy#10]
메뉴 선택 버튼 위치가 네비게이션 바 내부로 들어가야할 것 같아요!
![RecoredDetailView](https://user-images.githubusercontent.com/68676844/174008299-9c0c1e71-a9f7-4a3e-b0d8-c80319432404.png)

**Comment by Eunbi-Cho** [comment]
제가 오늘 PR 올린 파일에 수정했습니다!
