### ISSUE TITLE
저희 개발 마무리 단계에서 폰트 한 번에 수정하는 시간을 가져야할 것 같습니다!

### ISSUE THREAD

**Issue by YunSeok-Choi** [DeveloperAcademy-POSTECH/MC2-Team7-Larasy#15]
저희 개발 마무리 단계에서 폰트 한 번에 수정하는 시간을 가져야할 것 같습니다!
(지금 당장x)

_Originally posted by @JIWON1923 in https://github.com/DeveloperAcademy-POSTECH/MC2-Team7-Larasy/pull/14#discussion_r899033951_

**Comment by 100seo** [comment]
Fix #24
