### ISSUE TITLE
개발 끝난 후 프로젝트 명 변경

### ISSUE THREAD

**Issue by YunSeok-Choi** [DeveloperAcademy-POSTECH/MC2-Team7-Larasy#16]
# Recorder > Record

**Comment by mxnxxii** [comment]
Recorder > Record !!

**Comment by boskim22** [comment]
Re:cord, 렛코드(Let;s record).
영어단어를 일부러 문법적 오류를 통해 짓는 앱네임은
앱 스토어 기준으로 자동으로 오타수정이되어서 검색이 힘들다고 합니다.
