### ISSUE TITLE
SF symbol 폰트 깨짐 문제 해결

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MC2-Team7-Larasy#18]
Placeholder에서 마이크 깨졌던 문제 해결 방법 관련 문서입니다!
[블로그 바로가기](https://headintheclouds.tistory.com/18)
읽어보시고 해결 부탁드립니다!
@YunSeok-Choi

**Comment by YunSeok-Choi** [comment]
sketch에서는 해결이 되는 것 같은데 Xcode에서는 안되는 것 같습니다

**Comment by JIWON1923** [comment]
스케치 관련 글인 줄 몰랐네요!
[링크](https://swiftwithmajid.com/2021/12/21/sf-symbols-in-swiftui/)
`Text("Super star \(Image(systemName: "star"))")` 이렇게도 사용하네요!
확인해봤는데 placeholder에는 적용이 안 되네요

**Comment by YunSeok-Choi** [comment]
😂 제 xcode에서는 텍스트로 안불러와져요ㅠ

**Comment by JIWON1923** [comment]
수정 했습니다

![Simulator Screen Shot - iPhone 13 - 2022-06-18 at 13 46 15](https://user-images.githubusercontent.com/68676844/174423155-685683e4-932f-48f8-ae39-a127ab1f93b9.png)
