### ISSUE TITLE
[Feat] SearchView empty UI

### ISSUE THREAD

**Issue by mxnxxii** [DeveloperAcademy-POSTECH/MC2-Team7-Larasy#48]
## 이슈 상황
- 노래 검색을 진행하기 전, 아무런 노래 리스트가 없음

## 필요한 새로운 기능
- 검색을 진행하기 전에도 노래 검색 리스트 띄우기

## 해야 할 일 
- [x] 뷰 접근 시 키보드 포커스

**Comment by JIWON1923** [comment]
해당 태스크로만 보았을 때, 어떤 출력화면을 원하시는지 감이 잘 안 잡히네요!
사용자가 검색어를 입력하기 전에, 노래 검색 리스트가 띄워져 있어야하는것일까요?

제가 이해되는 방향은 아래 두 가지가 있을 것 같네요!
1. 검색어를 입력하지 않았다 혹은 리스트가 비어있다는 텍스트를 띄운다.
2. 최근 검색어를 보여주는 리스트를 띄운다. 

로미님이 어떤 작업을 원하는지 자세히 써 주시면 더 좋을 것 같아요~!

**Comment by mxnxxii** [comment]
> 해당 태스크로만 보았을 때, 어떤 출력화면을 원하시는지 감이 잘 안 잡히네요! 사용자가 검색어를 입력하기 전에, 노래 검색 리스트가 띄워져 있어야하는것일까요?
> 
> 제가 이해되는 방향은 아래 두 가지가 있을 것 같네요!
> 
> 1. 검색어를 입력하지 않았다 혹은 리스트가 비어있다는 텍스트를 띄운다.
> 2. 최근 검색어를 보여주는 리스트를 띄운다.
> 
> 로미님이 어떤 작업을 원하는지 자세히 써 주시면 더 좋을 것 같아요~!

1번의 경우, 텍스트필드에서 제공하는 문구인 '기록하고 싶은 음악, 가수를 입력하세요'와 똑같은 맥락의 말이 한번 더 적힌다고 생각해요!
똑같은 내용이 2번 나오면 ux적으로도  불필요하다고 생각합니다!!

저같은 경우, 이슈를 등록할 때 서치바 아래에 빈 화면이 아닌 노래 리스트(순서는 랜덤)가 나오는 화면을 생각하고 작성하였습니다 :D

혹시 쏘이님 더 이해 안가는 부분 있으면 다시 말씀해주세요!!

**Comment by JMM00** [comment]
> 
> 1번의 경우, 텍스트필드에서 제공하는 문구인 '기록하고 싶은 음악, 가수를 입력하세요'와 똑같은 맥락의 말이 한번 더 적힌다고 생각해요! 똑같은 내용이 2번 나오면 ux적으로도 불필요하다고 생각합니다!!
> 
> 저같은 경우, 이슈를 등록할 때 서치바 아래에 빈 화면이 아닌 노래 리스트(순서는 랜덤)가 나오는 화면을 생각하고 작성하였습니다 :D
> 
> 혹시 쏘이님 더 이해 안가는 부분 있으면 다시 말씀해주세요!!

로미님 말씀대로 빈화면에 노래 리스트를 넣으려고합니다. 현재 작업 상황은
<img src = "https://user-images.githubusercontent.com/41153398/192422477-40eef57a-cec8-4389-9fff-4d343a94ced1.png" width = "200" >
이런 모습인데 SearchView에 들어가자마자 노래 리스트가 떠 있어서 검색하도록 유도가 잘 되지 않는 것 같습니다. 

저의 의견은
1. '추천 검색어' 텍스트를 넣거나
2. 기존 검색 결과 리스트와 다르게 가수이름 또는 노래 제목만 나오게하여 차이를 주는 것이 좋을 것 같다는 생각입니다. 

혹시 다른 분들 생각은 어떤지 저와 생각이 같다면 어떤식으로 해결하는게 좋을지 의견남겨주시면 좋을 것 같습니다.

**Comment by mxnxxii** [comment]
> > 1번의 경우, 텍스트필드에서 제공하는 문구인 '기록하고 싶은 음악, 가수를 입력하세요'와 똑같은 맥락의 말이 한번 더 적힌다고 생각해요! 똑같은 내용이 2번 나오면 ux적으로도 불필요하다고 생각합니다!!
> > 저같은 경우, 이슈를 등록할 때 서치바 아래에 빈 화면이 아닌 노래 리스트(순서는 랜덤)가 나오는 화면을 생각하고 작성하였습니다 :D
> > 혹시 쏘이님 더 이해 안가는 부분 있으면 다시 말씀해주세요!!
> 
> 로미님 말씀대로 빈화면에 노래 리스트를 넣으려고합니다. 현재 작업 상황은 <img alt="" width="200" src="https://user-images.githubusercontent.com/41153398/192422477-40eef57a-cec8-4389-9fff-4d343a94ced1.png"> 이런 모습인데 SearchView에 들어가자마자 노래 리스트가 떠 있어서 검색하도록 유도가 잘 되지 않는 것 같습니다.
> 
> 저의 의견은
> 
> 1. '추천 검색어' 텍스트를 넣거나
> 2. 기존 검색 결과 리스트와 다르게 가수이름 또는 노래 제목만 나오게하여 차이를 주는 것이 좋을 것 같다는 생각입니다.
> 
> 혹시 다른 분들 생각은 어떤지 저와 생각이 같다면 어떤식으로 해결하는게 좋을지 의견남겨주시면 좋을 것 같습니다.

그려진 화면을 보니까 엘리님의 의견이 더 좋은 것 같네요!!
개인적인 의견으로는 추천 검색어 텍스트만 넣는 1번 의견이 더 좋은 것 같아요!!

텍스트는 추천 검색어 보다는 '추천 음악'으로 하는거 어떤가 싶네요!!
워딩을 검색어라고 하니까 개인적으로 조금 어색한 것 같아요 :)

**Comment by JMM00** [comment]
> 
> 그려진 화면을 보니까 엘리님의 의견이 더 좋은 것 같네요!! 개인적인 의견으로는 추천 검색어 텍스트만 넣는 1번 의견이 더 좋은 것 같아요!!
> 
> 텍스트는 추천 검색어 보다는 '추천 음악'으로 하는거 어떤가 싶네요!! 워딩을 검색어라고 하니까 개인적으로 조금 어색한 것 같아요 :)

의견 감사합니다! 우선은 추천 검색어로 작업 진행해보겠습니다. 혹시 다른 의견이 있으시다면 남겨주세요~!

**Comment by JMM00** [comment]
기존 음악 리스트 UI대로 제공 시 검색으로 유도가 잘 되지 않아 
1. 뷰 접근 시 키보드 포커스
2. top 10 노래 제목만 제공
2 가지 방안 중 의견이 1번으로 일치되어 키보드 포커스로 변경해서 진행합니다~!
